/**
 * FontLoader — Tahoe Widgets
 *
 * Mendaftarkan font Inter (variable font) yang dibundle di dalam
 * folder ekstensi langsung ke GNOME Shell St theme, tanpa butuh
 * install manual dari user.
 *
 * Cara kerja:
 *  1. Tulis @font-face CSS ke /tmp/tahoe-inter-fonts.css
 *     (path absolut ke folder fonts/ di dalam ekstensi)
 *  2. Load stylesheet itu ke St.Theme aktif
 *  3. Saat ekstensi di-disable, unload stylesheet-nya
 *
 * Struktur folder yang dibutuhkan:
 *
 *   tahoe-widgets@gnome/
 *   └── fonts/
 *       └── Inter.ttf    ← HANYA 1 FILE ini yang dibutuhkan
 *
 * Cara mendapatkan file Inter.ttf:
 *  1. Download Inter dari Google Fonts (fonts.google.com/specimen/Inter)
 *  2. Di dalam zip yang didownload, ambil file:
 *       Inter-VariableFont_opsz,wght.ttf
 *  3. Copy ke folder fonts/, rename jadi Inter.ttf
 *
 *  File variable font ini sudah mencakup semua weight (100–900)
 *  dalam 1 file — tidak perlu file terpisah per weight.
 */

import St  from 'gi://St';
import Gio from 'gi://Gio';

// Path sementara untuk CSS yang di-generate — tulis ke /tmp agar
// tidak perlu permission write ke direktori ekstensi (bisa read-only
// jika install system-wide di /usr/share/gnome-shell/extensions/).
const TMP_CSS_PATH = '/tmp/tahoe-inter-fonts.css';

/** @type {Gio.File | null} */
let _loadedStylesheet = null;

/**
 * Panggil sekali di extension.enable() — sebelum widget apapun dibuat.
 *
 * @param {string} extensionPath  — nilai dari `this.path` di dalam Extension class
 */
export function registerFonts(extensionPath) {
    if (_loadedStylesheet) return; // sudah di-load, skip

    const fontsDir = `${extensionPath}/fonts`;

    // ── Generate CSS @font-face ──────────────────────────────────────
    const css = _buildFontFaceCSS(fontsDir);
    if (!css) return; // file Inter.ttf tidak ada, berhenti di sini

    // ── Tulis ke /tmp ────────────────────────────────────────────────
    try {
        const tmpFile = Gio.File.new_for_path(TMP_CSS_PATH);
        const [ok] = tmpFile.replace_contents(
            new TextEncoder().encode(css),
            null,                                   // etag
            false,                                  // make_backup
            Gio.FileCreateFlags.REPLACE_DESTINATION,
            null,                                   // cancellable
        );
        if (!ok) {
            console.warn('[TahoeWidgets] fontLoader: gagal tulis CSS ke /tmp');
            return;
        }
        _loadedStylesheet = tmpFile;
    } catch (e) {
        console.warn('[TahoeWidgets] fontLoader: error tulis CSS —', e.message);
        return;
    }

    // ── Load ke St theme ─────────────────────────────────────────────
    try {
        const theme = St.ThemeContext
            .get_for_stage(global.stage)
            .get_theme();

        theme.load_stylesheet(_loadedStylesheet);
        console.log('[TahoeWidgets] fontLoader: Inter (variable font) berhasil didaftarkan dari', fontsDir);
    } catch (e) {
        console.warn('[TahoeWidgets] fontLoader: gagal load stylesheet —', e.message);
        _loadedStylesheet = null;
    }
}

/**
 * Panggil di extension.disable() untuk bersih-bersih.
 */
export function unregisterFonts() {
    if (!_loadedStylesheet) return;
    try {
        const theme = St.ThemeContext
            .get_for_stage(global.stage)
            .get_theme();
        theme.unload_stylesheet(_loadedStylesheet);
    } catch (e) {
        console.warn('[TahoeWidgets] fontLoader: gagal unload stylesheet —', e.message);
    }

    // Hapus file /tmp
    try { _loadedStylesheet.delete(null); } catch {}
    _loadedStylesheet = null;
    console.log('[TahoeWidgets] fontLoader: stylesheet dihapus');
}

/* ── Internal ─────────────────────────────────────────────────────────── */

/**
 * Bangun string CSS @font-face untuk Inter variable font.
 *
 * Menggunakan 1 file Inter.ttf (variable font) yang mencakup
 * semua weight 100–900 sekaligus — jauh lebih simpel dari
 * mendaftarkan file terpisah per weight.
 *
 * @param {string} fontsDir  — path absolut ke folder fonts/
 * @returns {string | null}  — null jika file tidak ditemukan
 */
function _buildFontFaceCSS(fontsDir) {
    let fontPath = `${fontsDir}/Inter.ttf`;
    if (!Gio.File.new_for_path(fontPath).query_exists(null)) {
        fontPath = `${fontsDir}/Inter-VariableFont_opsz,wght.ttf`;
        if (!Gio.File.new_for_path(fontPath).query_exists(null)) {
            console.warn(
                '[TahoeWidgets] fontLoader: Inter font tidak ditemukan di', fontsDir,
                '— pastikan Inter.ttf atau Inter-VariableFont_opsz,wght.ttf tersedia'
            );
            return null;
        }
    }

    // font-weight: 100 900  →  satu @font-face untuk semua weight
    // font-variation-settings 'opsz' tidak perlu di-set manual —
    // browser/Pango akan memilihnya otomatis berdasarkan font-size.
    return `/* Auto-generated by fontLoader.js — jangan edit manual */

@font-face {
    font-family: "Inter";
    font-style:  normal;
    font-weight: 100 900;
    src: url("file://${fontPath}") format("truetype");
}

@font-face {
    font-family: "Inter";
    font-style:  italic;
    font-weight: 100 900;
    src: url("file://${fontPath}") format("truetype");
}`;
}